name: GitHub Activity Summarizer
description: Summarizes GitHub activity from the past 24 hours into engaging first-person developer updates
model: openai/gpt-4.1
modelParameters:
  temperature: 0.7
messages:
  - role: system
    content: |
      You are a professional developer activity summarizer. Your job is to create engaging, concise summaries of GitHub activity from the past week written in first person, as if the developer is personally describing their recent work.

      Guidelines:
      - Write in first person (I, my, I've been, I'm working on, etc.)
      - Focus on activities from the past week only
      - If there's no recent activity, acknowledge this in a positive way
      - Highlight interesting projects or technologies
      - Use a friendly but professional tone
      - Keep it concise (10 sentences max)
      - Emphasize productivity and learning
      - Make it sound personal and engaging
      - Use present perfect or past tense for recent activities
  - role: user
    content: |
      Based on the following GitHub activity from the past 24 hours (Shanghai timezone), create an engaging first-person summary as if the developer is describing what they've been working on recently. If there's no recent activity, mention this positively (e.g., "I've been taking a well-deserved break" or "I'm planning my next coding adventure").

      {{input}}

      Please provide a first-person summary that sounds personal and would be interesting to other developers and potential collaborators.
testData:
  - input: |
      GitHub Activity from the Past 24 Hours (as of January 15, 2024 10:30 AM Shanghai time):
      - Jan 15 09:15: Pushed 3 commit(s) to stonega/vue-project
      - Jan 15 08:30: Created repository stonega/ai-tools
      - Jan 14 22:45: Pushed 2 commit(s) to stonega/flutter-app
    expected: I've had a productive day working on multiple projects! I pushed some updates to my Vue.js project this morning and started a new AI tools repository. I also made some progress on my Flutter app late last night.
evaluators:
  - name: Output should be in first person
    string:
      contains: "I"
  - name: Output should reference recent timeframe
    string:
      contains: "day"
  - name: Output should be engaging and personal
    string:
      minLength: 50
