name: Update README with GitHub Activity

on:
  schedule:
    # Run every Monday at 6 AM UTC
    - cron: "0 6 * * 1"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md" # Don't trigger on README changes to avoid infinite loops

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate README summary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: bun run index.ts

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update README with weekly GitHub activity"
            git push
          fi
